GET http://localhost:5005/api/v1/diffculty/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgyNTkyZGRjMDYyODA4NzVhM2M1NWQiLCJ1c2VybmFtZSI6IlVTRVIxIiwiaWF0IjoxNjg2MzIyOTY2LCJleHAiOjE2ODY5Mjc3NjZ9.rhlhUeRbl-zCzTV075-BhgP4LyrfLIMWKCBnvSsUemM

###
POST http://localhost:5005/api/v1/diffculty/add-diffculty
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgyNjBhYzI0NjJjNGJlNzI0Njc5MGMiLCJ1c2VybmFtZSI6IkFETUlOIiwiaWF0IjoxNjg2MzIzMTk0LCJleHAiOjE2ODY5Mjc5OTR9.SWIvFiN_W3z-7rf41MqZGEjlgWZUDrW3pnyghuBO1F0

{
    "difficultyName": "Extra",
    "score": 5
}